### ISSUE TITLE
attempt to index a nil value (global ‘Config’)

### ISSUE THREAD

**Issue by nemorinxyz** [i6h/connectqueue#1]
[ script:connectqueue] SCRIPT ERROR: @connectqueue/shared/sh_queue.lua:32: attempt to index a nil value (global ‘Config’)
[ script:connectqueue] > fn (@connectqueue/shared/sh_queue.lua:32)

**Comment by its4lion** [comment]
Fixed with the latest update. Thanks for letting me know!
